### ISSUE TITLE
Line

### ISSUE THREAD

**Issue by yPower** [Southclaws/ScavengeSurvive#508] opened 2018-03-27 22:29 UTC
@Southclaws 
C:\Users\BrazilianReal\Desktop\ScavengeSurvive-1759\pawno\include\Line.inc(63) : error 017: undefined symbol "Iterator@lin_Index"
C:\Users\BrazilianReal\Desktop\ScavengeSurvive-1759\pawno\include\Line.inc(63) : error 017: undefined symbol "Iterator@lin_Index"
C:\Users\BrazilianReal\Desktop\ScavengeSurvive-1759\pawno\include\Line.inc(63) : error 017: undefined symbol "Iter_Single@lin_Index"
C:\Users\BrazilianReal\Desktop\ScavengeSurvive-1759\pawno\include\Line.inc(63) : fatal error 107: too many error messages on one line

Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

4 Errors.

**Comment by Y-Less** [comment] 2018-03-27 22:47
I don't think that's a scavenge survive file, the only reason it is mentioned is that you put it in a folder called "ScavengeSurvive".  However, I can tell you the problem is probably using the wrong y_iterate version.  Make sure you've updated YSI and that that include uses the correct syntax.

**Comment by Y-Less** [comment] 2018-03-27 22:47
Correct me if I'm wrong @Southclaws

**Comment by yPower** [comment] 2018-03-27 23:12
You is True.

**Comment by yPower** [comment] 2018-03-27 23:22
But bro I use your include and give it:
C:\Users\BrazilianReal\Desktop\ScavengeSurvive-1759\pawno\include\YSI\..\YSI_Coding\..\YSI_Coding\y_malloc/heapalloc.inc(132) : warning 235: public function lacks forward declaration (symbol "VA_OnScriptInit")
C:\Users\BrazilianReal\Desktop\ScavengeSurvive-1759\pawno\include\Line.inc(63) : error 017: undefined symbol "Iterator@lin_Index"
C:\Users\BrazilianReal\Desktop\ScavengeSurvive-1759\pawno\include\Line.inc(63) : error 017: undefined symbol "Iterator@lin_Index"
C:\Users\BrazilianReal\Desktop\ScavengeSurvive-1759\pawno\include\Line.inc(63) : error 017: undefined symbol "Iter_Single@lin_Index"
C:\Users\BrazilianReal\Desktop\ScavengeSurvive-1759\pawno\include\Line.inc(63) : fatal error 107: too many error messages on one line

Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase


4 Errors.

**Comment by yPower** [comment] 2018-03-27 23:22
Can you paste the true link of YSI that is for use

**Comment by yPower** [comment] 2018-03-27 23:22
@Y-Less

**Comment by Y-Less** [comment] 2018-03-27 23:26
Ignore the warning.  As for the errors, I have no idea without the code!

**Comment by yPower** [comment] 2018-03-27 23:27
type I download it https://github.com/pawn-lang/YSI-Includes and give this errors, have idea?

**Comment by yPower** [comment] 2018-03-27 23:29
Line 51:
Iterator:	lin_Index[MAX_LINE];

Line 63:
	new id = Iter_Free(lin_Index);

**Comment by yPower** [comment] 2018-03-27 23:29
@Y-Less

**Comment by Y-Less** [comment] 2018-03-28 00:18
That code isn't even right.

**Comment by Southclaws** [comment] 2018-03-28 08:02
Y_Less is right, `Line.inc` is from https://github.com/Southclaws/samp-linegen which was renamed and cleaned up - it works with the latest YSI.

The main issue here is I'm not maintaining this repo any more. It won't compile and half the code is missing because I'm moving it to packages. The only advice I can give is to try build 1192 as that was the last stable build that most people use.

**Closed by Southclaws** 2018-03-28 08:02 UTC
