### ISSUE TITLE
Server "halts" if a players stays at the login screen

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#417] opened 2017-04-06 10:04 UTC
It doesn't really halt, it prevents other players from joining if a player just stays at the login screen.

**Comment by Southclaws** [comment] 2017-04-06 10:12
Do you have any logs? Primarily any `LoadAccount` and `LOGPROMPT` events .

I've never heard of this issue before and I can't imagine how it could happen, no real state is passed between player logins so I'm going to blame y_dialog for this one.

What does the halt look like? Does the login screen not show for other players?

**Comment by Southclaws** [comment] 2017-04-06 11:54
It would be a 2-player scenario:
1. p1 with existing account connects, does not log in
2. p2 either new or existing account connects
we can test this later today on `master` and `redis` I would make a guess that it would not repro on `redis` as I've modified a lot of the connect/dialog code.

**Comment by Virtxmedia** [comment] 2017-04-06 12:12
Sounds pretty bad, if that persists A class unless there is a workaround to log in and play. I wonder how many players you can get stacked up :P

**Comment by Southclaws** [comment] 2017-04-13 19:01
Just tested on `redis` branch with @Virtxmedia and could not reproduce, looks like this is fixed on the latest version (I did quite a lot of rewriting of login/registration routing code).

**Closed by Southclaws** 2017-04-13 19:01 UTC
Labels: [state] Confirmation Needed

**Comment by viruxe** [comment] 2017-04-14 21:04
```
[19:27:07] [connection] incoming connection: 213.226.141.113:60275 id: 0
[19:27:07] [join] [RCM]Kaija has joined the server (0:213.226.141.113)
[19:27:07] INFO: [RemoveObjects_FirstLoad] Created session data for [RCM]Kaija
[19:27:07] [JOIN] [RCM]Kaija joined
[19:27:13] [LoadAccount] [RCM]Kaija (account exists, prompting login) Alive: 1 Last login: Friday Apr 14 2017 at 14:18:10
[19:27:13] [LOGPROMPT] [RCM]Kaija is logging in
[19:28:05] [connection] 213.226.141.113:60278 requests connection cookie.
[19:28:36] Kicking 213.226.141.113 because they didn't logon to the game.
[20:07:26] [connection] 213.226.141.113:61752 requests connection cookie.
[20:07:57] Kicking 213.226.141.113 because they didn't logon to the game.
```
Kaija is not connected.

**Comment by Southclaws** [comment] 2017-04-15 09:36
Oh that's a different issue, `Kicking 213.226.141.113 because they didn't logon to the game` means the main server thread is busy processing something - most likely in an infinite loop. Seems to have been passively fixed on `redis` branch anyway so you could try and port over some of the code or wait for that branch to be finished. Right now I'm focusing on finishing that branch and don't really want to go back and try to fix things in an older version.
