### ISSUE TITLE
Items duplicating in backpack

### ISSUE THREAD

**Issue by GuerrillaLS** [Southclaws/ScavengeSurvive#370] opened 2016-12-29 14:58 UTC
Didn't have a chance to test this further. Some items ( Mostly: Key, Crowbar, Screwdriver and other tools ) which are often kept in your inventory. They somehow get duplicated once they reach backpack. It happens so commonly I usually have to hide about 2-3 duplicated keys per restart. I'm guessing it has something to with auto backpack loader.

**Comment by Southclaws** [comment] 2016-12-30 11:17
This could have been caused by the memory corruption that was happening on the test server yesterday (which I've since fixed). I'm going to assume/hope it was as I haven't seen anything like this while developing the new stuff in the past few months. I'll keep an eye open and I'll keep this issue open in case it appears again though. Thanks!

**Comment by Southclaws** [comment] 2017-01-17 00:15
Fixed in 1759

**Closed** 2017-01-17 00:15 UTC
Labels: bug, rare
